### PR TITLE
Fix duplicates for bg crash

### LINKED ISSUE #767: Duplicates!
We found 21M duplicates on one of our cluster.

Use case: replace-mode

Distribution:
```
4,4,4,5,5,7,12,15,19,22,23,24,48,73,102,115,137,164,168,179,198,277,296,372,548,564,636,744,2814,3477,8654
```

And about 20M more of 2 and 3.

We suspect `setVersion(1)` in both x-fix and bg, we will have to see if it helps.

* This code was not modified lately, so there may be more causes for that.

### PR DESCRIPTION
**Pull request by bryaakov**
Looks like it fixes #767 but there might as well be more reasons, see for one example #771.

### CODE REVIEW

File: server/cmwell-bg/src/main/scala/cmwell/bg/ImpStream.scala [hunk 1]
```diff
@@ -533,6 +577,22 @@ class ImpStream(partition: Int,
           )
         )
 
+        val checkRecoveryState = builder.add(
+          Flow[BGMessage[Command]].map { cmd =>
+            if(isRecoveryMode || isRecoveryModePriority) cmd.offsets.foreach { o =>
```
Comment (e-orz) [inline server/cmwell-bg/src/main/scala/cmwell/bg/ImpStream.scala]: change to forall

File: server/cmwell-bg/src/main/scala/cmwell/bg/ImpStream.scala [hunk 2]
```diff
@@ -333,61 +362,81 @@ class ImpStream(partition: Int,
...
-              val statusTracking = trackingIds.map {
-                StatusTracking(_, 1)
+          .flatMap { i =>
+            val ini: (IndexCommand, Option[DateTime]) = IndexNewInfotonCommand(i.uuid, true, i.path, Some(i), i.indexName,
+              trackingIds.map(StatusTracking(_, 1))) -> Some(i.lastModified)
+            if (previous.isEmpty) {
+              Future.successful(List(BGMessage(offsets, Seq(ini))))
+            } else if(previous.get.isSameAs(latest)) {
+              if(!isRecoveryRequired) {
+                logger.warn(s"Previous [${previous.get.uuid}] isSameAs Latest but recoveryMode is off, this should never happen.")
```
Comment (e-orz) [inline server/cmwell-bg/src/main/scala/cmwell/bg/ImpStream.scala]: It can happen (e.g. parents). but keep the warning, just change the phrase.

File: server/cmwell-bg/src/main/scala/cmwell/bg/ImpStream.scala [hunk 3]
```diff
@@ -533,6 +581,22 @@ class ImpStream(partition: Int,
           )
         )
 
+        val checkRecoveryState = builder.add(
+          Flow[BGMessage[Command]].map { cmd =>
+            if (isRecoveryMode || isRecoveryModePriority) {
+              if(cmd.offsets.forall(o => isRecoveryMode && o.topic == persistCommandsTopic && o.offset >= initialWriteHead)) {
```
Comment (e-orz) [inline server/cmwell-bg/src/main/scala/cmwell/bg/ImpStream.scala]: As you told me, a command can have priority and non priority offsets and the logic need to be changed
